books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("form/", views.add, name="url_form"),
    path("list/", views.Booklist, name="url_list"),
    path("search_books/", views.search_book, name="url_search"),
    path("update/<int:pk>/", views.update, name="url_update"),
    path("delete/<int:pk>/", views.delete, name="url_delete"),
    path("filter/<int:min>/<int:max>/", views.preco_filtro, name="url_filter"),
]

mysite/urls.py
from books import urls as primeiroapp_urls
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(primeiroapp_urls)),
]

primeiroapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("form/", views.add, name="url_form"),
    path("list/", views.Booklist, name="url_list"),
    path("update/<int:pk>/", views.update, name="url_update"),
    path("delete/<int:pk>/", views.delete, name="url_delete")
]

books/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
        name = models.CharField("Nome Completo", max_length=200)
        email = models.CharField("Email", max_length=200, blank=True, null=True)

        def __str__(self):
            return self.name


class Category(models.Model):
    name = models.CharField("Categoria", max_length=200)
    description = models.TextField("Descricao")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField("Titulo", max_length=200)
    author = models.ManyToManyField(Author, verbose_name="Autores")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Categoria", blank=True, null=True)
    isbn = models.CharField("ISBN", max_length=13, unique=True, help_text="13 Caracteres <a href='/'> ISBN number </a>", null=True)
    launch = models.DateField("Lançamento", blank=True, null=True)
    edition = models.CharField("Edição", max_length=200, blank=True, null=True)
    genre = models.CharField("Gênero Textual", max_length=200, blank=True, null=True)
    publisher = models.CharField("Editora", max_length=200, blank=True, null=True)
    price = models.FloatField("Valor", default=100)
    description = models.TextField("Descrição", blank=True, null=True)
    # image = models.imageField(upload_to="livraria/media", blank=True)

    def __str__(self):
        return self.title


class User(models.Model):
    username = models.CharField("Usuário", max_length=15)
    firstname = models.CharField("Nome", max_length=200, null=True)
    secondname = models.CharField("Sobrenome", max_length=200, null=True)
    email = models.CharField("Email", max_length=200)
    cell_number = models.CharField("Telefone", max_length=12, null=True)
    password = models.CharField("Senha", max_length=12)
    address = models.CharField("Endereço", max_length=255, null=True)

    def __str__(self):
        return self.username


class CartItem(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="Usuário", blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Livro", blank=True, null=True)
    quantity = models.IntegerField("Quantidade")

    def __str__(self):
        return self.book.title

books/forms.py
from django.forms import ModelForm
from .models import Book, User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "firstname", "secondname", "password", "email", "cell_number"]


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "description", "isbn", "launch", "edition", "category", "genre", "publisher", "price"]

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Book
from .models import User
from .forms import BookForm
import datetime
import requests


def home(request):
    data = {"today": datetime.datetime.now(), "users": User.objects.all()}
    print(data)
    return render(request, "books/home.html", data)


def Booklist(request):
    data = {"books": Book.objects.all()}
    return render(request, "books/book_list.html", data)


def add(request):
    data = {}
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("url_list")
    data["form"] = form
    return render(request, "books/form.html", data)


def update(request, pk):
    data = {}
    book = Book.objects.get(pk=pk)
    form = BookForm(request.POST or None, instance=book)

    if form.is_valid():
        form.save()
        return redirect("url_list")

    data["form"] = form
    data["book"] = book
    return render(request, "books/form.html", data)


def delete(request, pk):
    book = Book.objects.get(pk=pk)
    book.delete()
    return redirect("url_list")

def preco_filtro(request, min, max):
    data = {"books": Book.objects.filter(price__gte=min, price__lte=max).values()}
    return render(request, "books/book_list.html", data)

def search_book(request):
    if 'searched' in request.POST:
        searched = request.POST['searched']
        return render(request, "books/search.html", searched)
    else:
        return render(request, "books/search.html", {})

primeiroapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Book
from .models import User
from .forms import BookForm
import datetime


def home(request):
    data = {"today": datetime.datetime.now(), "users": User.objects.all()}
    print(data)
    return render(request, "primeiroapp/home.html", data)


def Booklist(request):
    data = {"books": Book.objects.all()}
    return render(request, "primeiroapp/book_list.html", data)


def add(request):
    data = {}
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("url_list")
    data["form"] = form
    return render(request, "primeiroapp/form.html", data)


def update(request, pk):
    data = {}
    book = Book.objects.get(pk=pk)
    form = BookForm(request.POST or None, instance=book)

    if form.is_valid():
        form.save()
        return redirect("url_list")

    data["form"] = form
    data["book"] = book
    return render(request, "primeiroapp/form.html", data)


def delete(request, pk):
    book = Book.objects.get(pk=pk)
    book.delete()
    return redirect("url_list")

books/templates/books/book_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <title> Livros </title>
</head>
<body>
    <header class="px-3">
        <nav class="navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="/">Livraria</a>
            <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item ">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_list'%}">Livros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_form'%}"> Adicionar</a>
              </li>
            </ul>
            </div>
                <form class="d-flex" method="POST" action="{% url 'url_search' %}">
                    {% csrf_token %}
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
        </nav>
   </header>
        <h1 class="display-4"> Livros </h1>
    <div class="container my-3">
        <a href="{% url 'url_filter' 0 100 %}"><button class="btn btn-outline-primary mx-1"> 0 - 100 </button></a>
        <a href="{% url 'url_filter' 100 200 %}"><button class="btn btn-outline-primary mx-1"> 100 - 200 </button></a>
        <a href="{% url 'url_filter' 200 300 %}"><button class="btn btn-outline-primary mx-1"> 200 - 300 </button></a>
        <a href="{% url 'url_list' %}"><button class="btn btn-outline-primary mx-1"> Todos </button></a>
    </div>


    <div class="container">
        <div class="row">
        {% for book in books %}
            <div class="col-3">
                <div class="card">
                  <img src="..." class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">${{ book.price}}</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <h5 class="card-title px-2"> Autores </h5>
                        {% for author in book.author.all %}
                        <li class="list-group-item"> {{ author.name }}</li>
                        {% endfor %}
                  </ul>
                  <div class="card-body d-flex justify-content-end">
                        <a href="{% url 'url_update' book.id%}"><button class="btn btn-outline-primary mx-1"> Editar </button></a>
                        <a href="{% url 'url_delete' book.id%}"><button class="btn btn-outline-danger"> Deletar </button></a>
                  </div>
                </div>
            </div>
         {% endfor %}
        </div>
    </div>
</body>
</html>

books/templates/books/form.html
<!doctype html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <!--  <link rel="stylesheet"  href="{% static 'css/form.css' %}" /> -->
    <link rel="stylesheet"  href="{% static 'css/form.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- <script src="{% static 'js/form.js' %}"> </script> -->
    <title>Adicionar Livro</title>
</head>
<body onload="styleForm()">
    <header class="px-3">
        <nav class="navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="/">Livraria</a>
            <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item ">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_list'%}">Livros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_form'%}"> Adicionar</a>
              </li>
            </ul>
            </div>
        </nav>
   </header>
    <div class="container py-4">
        <form method="POST">
            {% csrf_token %}
            <div class="row py-2">
                <div class="col" >
                    <label for="id_title">Título</label>
                    {{ form.title }}

                </div>
              <div class="col">
                    <label for="id_isbn">ISBN</label>
                    {{ form.isbn }}
              </div>
            </div>
            <div class="row py-2">
                <div class="col-4">
                    <label for="id_author">Autor</label>
                    {{ form.author }}
                </div>
                <div class="col">
                    <label for="id_launch">Lançamento</label>
                    {{ form.launch }}
                </div>
                 <div class="col">
                    <label for="id_genre">Genero</label>
                    {{ form.genre }}
                </div>
                 <div class="col">
                    <label for="id_category">Categoria</label>
                    {{ form.category }}
                </div>
            </div>
             <div class="row py-2">
              <div class="col-4">
                    <label for="id_description">Descrição</label>
                    {{ form.description }}
              </div>
                 <div class="col">
                    <label for="id_edition">Edição</label>
                    {{ form.edition }}
                </div>
                 <div class="col">
                    <label for="id_publisher">Editora</label>
                    {{ form.publisher }}
                </div>
            </div>
            <div class="row py-2">
                 <div class="col-3">
                    <label for="id_price">Preço</label>
                    {{ form.price }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary"> Salvar </button>
        </form>
    </div>
    <!--  <div>
        <form>
            {% csrf_token %}
            {{ form.as_p }}
        </form>
    </div>
    -->

</body>
</html>

books/templates/books/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>Home</title>
</head>
<body>
   <header class="px-3">
        <nav class="navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="#">Livraria</a>
            <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item ">
                <a class="nav-link" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_list'%}">Livros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_form'%}"> Adicionar</a>
              </li>
            </ul>
            </div>
        </nav>
   </header>
    <div>
        <h2> {{ today }} </h2>
       {% for user in users %}
        <h2> Bom dia {{ user.firstname }}</h2>

        {% endfor %}

    </div>
</body>
</html>

books/templates/books/search.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <title> Busca </title>
</head>
<body>
    <header class="px-3">
        <nav class="navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="/">Livraria</a>
            <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item ">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_list'%}">Livros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_form'%}"> Adicionar</a>
              </li>
            </ul>
            </div>
                <form class="d-flex" method="POST">
                    {% csrf_token %}
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
        </nav>
   </header>
    {% if searched %}
        <h1 class="display-4"> Você procurou por {{ searched }} </h1>
    {% else %}
        <h1 class="display-4"> Faça uma busca </h1>
    {% endif  %}
    <div class="container my-3">
        <a href="{% url 'url_filter' 0 100 %}"><button class="btn btn-outline-primary mx-1"> 0 - 100 </button></a>
        <a href="{% url 'url_filter' 100 200 %}"><button class="btn btn-outline-primary mx-1"> 100 - 200 </button></a>
        <a href="{% url 'url_filter' 200 300 %}"><button class="btn btn-outline-primary mx-1"> 200 - 300 </button></a>
        <a href="{% url 'url_list' %}"><button class="btn btn-outline-primary mx-1"> Todos </button></a>
    </div>


    <div class="container">
        <div class="row">
        {% for book in books %}
            <div class="col-3">
                <div class="card">
                  <img src="..." class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">${{ book.price}}</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <h5 class="card-title px-2"> Autores </h5>
                        {% for author in book.author.all %}
                        <li class="list-group-item"> {{ author.name }}</li>
                        {% endfor %}
                  </ul>
                  <div class="card-body d-flex justify-content-end">
                        <a href="{% url 'url_update' book.id%}"><button class="btn btn-outline-primary mx-1"> Editar </button></a>
                        <a href="{% url 'url_delete' book.id%}"><button class="btn btn-outline-danger"> Deletar </button></a>
                  </div>
                </div>
            </div>
         {% endfor %}
        </div>
    </div>
</body>
</html>

primeiroapp/templates/primeiroapp/add.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Adicionar Livro</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Salvar </button>
    </form>


    <div>
        <a href="{% url 'home'%}"> Home </a>
    </div>
</body>
</html>

primeiroapp/templates/primeiroapp/book_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <title> Livros </title>
</head>
<body>
    <header class="px-3">
        <nav class="navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="/">Livraria</a>
            <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item ">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_list'%}">Livros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_form'%}"> Adicionar</a>
              </li>
            </ul>
            </div>
                <form class="d-flex" method="POST">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
        </nav>
   </header>
        <h1> Livros </h1>
    <div class="container">
        <div class="row">
        {% for book in books %}
            <div class="col-3">
                <div class="card">
                  <img src="..." class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">${{ book.price}}</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <h5 class="card-title px-2"> Autores </h5>
                        {% for author in book.author.all %}
                        <li class="list-group-item"> {{ author.name }}</li>
                        {% endfor %}
                  </ul>
                  <div class="card-body d-flex justify-content-end">
                        <a href="{% url 'url_update' book.id%}"><button class="btn btn-outline-primary mx-1"> Editar </button></a>
                        <a href="{% url 'url_delete' book.id%}"><button class="btn btn-outline-danger"> Deletar </button></a>
                  </div>
                </div>
            </div>
         {% endfor %}
        </div>
    </div>
</body>
</html>